### ISSUE TITLE
Can IntersectionObserver be used instead of intervals?

### ISSUE THREAD

**Issue by mordechaim** [onderonur/react-infinite-scroll-hook#15]
Love this great library.

I was thinking timers weren't the most performant way of checking the boundaries. Should we instead rely on the [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) API?

**Comment by onderonur** [comment]
I guess, you are right on point. I was thinking the same thing and actually if it comes logical to other people, it might worth to try. I even have a intersection observer hook and it could be used in here.
Using interval was an escape hatch at the beginning. But the package kept growing thanks to all the great people using it. There are even some PRs ready to be reviewed and I think one of them was about not using intervals. And I will definitely try intersection observer too. The only downside is you will need to use some polyfill for older browers. But we could just set some option to use interval version, or if it complicates things, people always can use this version.
Unfortunately I'm a little busy at work nowadays and couldn't give too many attention to my open source projects. But definitely there will be updates soon. Thanks for the great idea again!

**Comment by mordechaim** [comment]
I decided to implement my own solution; although the API is not compatible with your, you can use some ideas. I commented extensively to understand what's flying.

``` javascript

export function useInfiniteScroll({ callback, threshold = 0 }) {
    // we use state instead of refs to force re-render on element changes
    const [element, setElement] = useState()
    const [container, setContainer] = useState()

    // closure buster; allow changing the callback on renders without recreating the observer
    const callbackRef = useRef()
    callbackRef.current = callback

    useEffect(() => {
        if (!element)
            return

        const topMargin = -(100 + (100 * threshold))
        const bottomMargin = 100 * threshold

        const observer = new IntersectionObserver(async entries => {
            let hasMore = true
            if (!entries[0].isIntersecting) {

                // Recursive function to keep loading if the loaded values still doesn't fill entire viewport.
                // Must not return before load completes, otherwise it will be called millions of times.
                // Best is to use an async function as the callback
                const executeCallback = async () => {
                    if (!hasMore || !callbackRef.current)
                        return hasMore

                    let bottom
                    // we use the actual container's size and not the entry's boundingClientRect since 
                    // we run recursively and the entry doesn't update
                    if (container) {
                        const rect = container.getBoundingClientRect()
                        bottom = rect.bottom + (rect.height * threshold)
                    } else {
                        bottom = window.innerHeight + (window.innerHeight * threshold)
                    }

                    if (element.getBoundingClientRect().bottom >= bottom)
                        return hasMore

                    hasMore = await callbackRef.current()
                    return await executeCallback()
                }

                hasMore = await executeCallback()
            }

            if (!hasMore)
                observer.disconnect()

            // By using margins we flatten the bounds into a horizontal line.
            // isIntersecting reflects whether the element touches the proverbial line.
        }, { root: container, rootMargin: `${topMargin}% 0% ${bottomMargin}%` })

        observer.observe(element)

        return () => {
            observer.disconnect()
        }
    }, [element, container, threshold])

    // passing them to refs will be handled as a callback ref
    return { element: setElement, container: setContainer }
}
```

Typical usage:

```javascript
function MyList(props) {
    const [items, setItems] = useState([])

    const loadMore = async () => {
        const result = await callMyApi()
        setItems(prev => [...prev, ...result])

        // return if there's potentially more to load
        // assume we know the server responds with maximum of 25 items at a time
        // if the count is less we can sure know there's nothing more to load
        return result.length === 25
    }

    // you can also destructure 'container'
    const { element } = useInfiniteScroll({ loadMore, threshold: .25 })

    return <div ref={element}>
        {items.map(i => <MyItem/>)}
    </div>
}
```

`threshold` is calculated as percentages of the bottom of the container's bounds (or viewport if no container is set):
- `0` (default) means the element left the bottom of the viewport
- `-0.5` means the element left the center of the viewport
- `0.5` means the element left the bottom plus half the height of the viewport.

You can use any value, these examples are just to illustrate its usage.

`callback` must not return before the new items completed loading, it should usually be an async function.
To pause loading more but still allow loading at some time later you should not return `false` in the callback, as it will completely stop observing the bounds. Instead, set the callback to `undefined`. Setting back the callback will restart calling it when needed.

**Comment by onderonur** [comment]
Hi!

I've just published a new major version (v4) and it uses `IntersectionObserver` under the hood.

It uses another package of mine ([react-intersection-observer-hook](https://github.com/onderonur/react-intersection-observer-hook)), so it was easier than I've thought actually 😄. 

Unfortunately, I haven't used your code sample but it gave me a lot of ideas. So, thanks for the great idea! 🎉🎊

Thanks!
