### ISSUE TITLE
Preferred method for handling errors?

### ISSUE THREAD

**Issue by cheshireoctopus** [onderonur/react-infinite-scroll-hook#16]
Hello!

Thank you for your work on this library. Doing a bit of due diligence before bringing it into a project.

Noticed a weird case involving error handling that causes an infinite loop.

To reproduce:

```
async function handleLoadMore() {
  setLoading(true)

  try {
    // API fetch typically here, but forcing an error
    throw 'Uh oh'
  } catch (error) {
    setError(true)
  }
}

const infiniteRef = useInfiniteScroll({
  loading,
  hasNextPage,
  onLoadMore: handleLoadMore,
  scrollContainer,
});
```

If the function `onLoadMore` encounters an error, it will continue getting called and enter an infinite loop.

After some trial and error, it seems like turning the loading off or setting `hasNextPage` to false when an error is encountered prevents this:

```
async function handleLoadMore() {
  setLoading(true)

  try {
    // API fetch typically here, but forcing an error
    throw 'Uh oh'
  } catch (error) {
    setError(true)
    setHasNextPage(false)
  }
}
```

Curious if this is the preferred way to handle errors? 

Wondering if the the library should handle this internally, so that if an error is raised this condition can no longer be met:

https://github.com/onderonur/react-infinite-scroll-hook/blob/master/src/useInfiniteScroll.ts#L127

**Comment by onderonur** [comment]
Great question actually. Personally I use the same method as well. 
I set an `hasError` flag and give it to `hasNextPage` like `hasNextPage: !hasError & hasNextPage`.
This way, you can set `hasError` to false with a button click etc to create some sort of a `try again`  feature.
I'm not sure how we can handle this kind of a feature in the scroll hook. Of course we can check for errors and if `onLoad` function throws an error, we can simply stop everything. But letting it start again would need some imperative method to access internals of the hook. The most declarative way I can think of is the method you described.
So I can say that is a valid practice to use it like that. I'm gonna definitely add this to `README.md`.
Thanks!

**Comment by cheshireoctopus** [comment]
@onderonur - appreciate the response and you adding this to the `README`.

Please feel free to close this ticket as you see fit (in case you want to keep it as reminder for updating `README`).
