### ISSUE TITLE
Can't get it to work with horizontal scrolling

### ISSUE THREAD

**Issue by cloudorbush** [onderonur/react-infinite-scroll-hook#20]
Any tips would be greatly appreciated.

**Comment by onderonur** [comment]
Hi!

I've just published **v4** and now we have a new API to create infinite scrolling. I've just updated `README.md` and will provide a basic migration guide soon.
You can check [here](https://github.com/onderonur/react-infinite-scroll-hook/blob/master/example/examples/InfiniteListWithHorizontalScroll.tsx) for a horizontal scrolling example created by using the new API.  
You can also see it in action on [here](https://onderonur.github.io/react-infinite-scroll-hook/). You just need to select `Horizontally Scrollable List` or `Reversed Horizontally Scrollable List` type 🙂.

Thanks again!

**Comment by cloudorbush** [comment]
wow awesome!
