### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by rubencanovaca** [onderonur/react-infinite-scroll-hook#23]
I'm trying to use your library, but doesn't work

Could you help me, please?

**Comment by onderonur** [comment]
Hi!

I've cloned your project and started it with a dummy API.
First of all, I don't have much knowledge about Redux Toolkit. But I've done some debugging and here is what I've found.
You can give any function to `onLoadMore` and it will call that when it needs to trigger infinite loading.
So, when I give some dummy function like:
```ts
const foo = () => { console.log("hello") };
```
I see that we have this `hello` on the console outputs. So, we don't have something wrong with the hook. But there must be another thing that makes this fail.

As I said, I don't have much knowledge about Redux Toolkit. I did use Redux a lot, but dropped using it like 1 year ago and I really don't know how the toolkit works internally.
If I'm right, you are using `fetchMoreItems` action as your `onLoadMore` callback.
And in `lootSlice`, you have a reducer called `fetchMoreItems` and it calls your `asyncFetchItems` thunk. I understand the idea. But I'm not sure if toolkit works like this.

I've tried the code below and it works.
But I wouldn't recommend using it directly. 
Please check Redux Toolkit docs to find a proper solution. 🙂 

```ts
// src\components\LootsList\LootsList.tsx
function LootsList({ loots }: Props) {
  const hasNextPage = useAppSelector(selectHasNextPage);
  const disabled = !!useAppSelector(selectError);

  const allItems = useAppSelector(selectAllItems);
  const dispatch = useDispatch();

  const handleLoadMore = useCallback(() => {
    dispatch(asyncFetchItems({ start: allItems.length, limit: 20 }));
  }, [allItems.length, dispatch]);

  const [infiniteRef] = useInfiniteScroll({
    loading: useAppSelector(selectStatus) === "loading",
    disabled,
    hasNextPage,
    onLoadMore: handleLoadMore,
    rootMargin: "0px 0px 400px 0px",
  });

  return (
    <div className="loots-list">
      <List data-test="item-list">
        {loots.map((loot: Loot) => (
          <LootsListItem key={loot._id} loot={loot} />
        ))}
        {hasNextPage && <div ref={infiniteRef}>Loading</div>}
      </List>
    </div>
  );
}
```

Thanks!
