### ISSUE TITLE
Couldnt use it with standard div

### ISSUE THREAD

**Issue by tcagkansokmen** [onderonur/react-infinite-scroll-hook#24]
Here's my code below.
It doesnt trigger "nextPage" function, while I scroll down (at the bottom of page).

whats wrong?

```

  const [infiniteRef] = useInfiniteScroll({
    loading,
    hasNextPage,
    onLoadMore: nextPage,
    disabled: !!error,
    rootMargin: '0px 0px 400px 0px',
  })
```

```

        <div className="my-content" ref={infiniteRef}>
          <div className="row" >
            <div className="col-sm-12">
              <div className="row">
                {product_list.data.map((item, i) => (
                  <div className="col-md-3 col-sm-6 col-6">
                    <ProductCard {...item} />
                  </div>
                ))}
              </div>
            </div>
        </div>
```

**Comment by onderonur** [comment]
Hi!

We need to use `infiniteRef` on the sentry of our list. Using it on the container of the list was the approach before v4.
With v4, the API is changed to make it more flexible and easy to implement different type of lists.
"Sentry" can be some "loading" indicator, some empty div or last item of your list etc.
The idea is, when our sentry becomes visible on the screen or it comes near to be visible, it will trigger `onLoadMore` callback.
So, we need to place the sentry based on our scroll direction (to bottom if we want to scroll to bottom, to top if we want to scroll to top like a chat message box etc. Same approach can be used with horizontal scrolling too.)
You can check [examples](https://github.com/onderonur/react-infinite-scroll-hook/tree/master/example/examples) folder for lists with different layouts.
And there are example projects to use this hook with [swr](https://github.com/onderonur/tmdb-explorer) or [Apollo GraphQL](https://github.com/onderonur/rick-and-morty-graphql).

I will add this answer to README too. It may clarify how to use the hook.

I'm not closing this issue for now. You can comment here your situation and progress. I will try to help 🙂

Thanks!

**Comment by onderonur** [comment]
Hi!

Since there are no further comments for a while, I'm guessing that the problem was solved by the new API.

I'm closing this issue.

Thanks!
