### ISSUE TITLE
How to force a reload of the already rendered list ?

### ISSUE THREAD

**Issue by jacargentina** [onderonur/react-infinite-scroll-hook#28]
I have a search term Input, so the infinite scroll is affected by that: when I change the criteria for that Input, I need all items to be cleared and re-fetch with the new criteria. How can I achieve that?

**Comment by onderonur** [comment]
This issue depends on which state/cache management method you are using actually. Built-in react state, redux, react-query, swr, apollo etc. has their own methods to handle this kind of situations and this is not so dependant on this package I think. So, you can check `useInfiniteQuery` hook if you use react-query from [infinite queries section](https://react-query.tanstack.com/guides/infinite-queries) for example.

I also have a similar search page [here](https://github.com/onderonur/tmdb-explorer/blob/master/src/search/SearchResults.tsx) created by using [swr](https://swr.vercel.app/) (I will probably migrate it to react-query soon btw) and this hook.

**Comment by khaledosama999** [comment]
@onderonur  The link that leads to the page is broken, can you please update it
