### ISSUE TITLE
useRef() should be called with an initial value, undefined is not really valid there

### ISSUE THREAD

**Issue by ericblade** [onderonur/react-infinite-scroll-hook#3]
https://github.com/onderonur/react-infinite-scroll-hook/blob/7ea63e76147ca6cfbeb57468392a821afd021fad/src/useInfiniteScroll.js#L16

... should be using useRef(null) rather than useRef() .  

Please see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35572

**Comment by onderonur** [comment]
Nice catch! Fixed this with version 2.0.1.
#4 
Thanks
