### ISSUE TITLE
Now we have infinite bottom scroll, do we have plans add infinite top scroll?

### ISSUE THREAD

**Issue by Martian2Lee** [onderonur/react-infinite-scroll-hook#5]

**Comment by onderonur** [comment]
It would be a cool feature for projects like messengers, chat apps etc. I was considering to add this feature a little while ago. Tracking the top of the window/parent container is nearly the same as tracking the bottom. But the main point is, if you want an infinite scrolling page/block with "reversed" direction, you would probably want to start your scroll position at the bottom of it. Handling the scroll can be passed to the user land. But it may also be handled by this library itself. Yet, it may cause strange bugs or restrictions.

When I find a good way to support this, definitely would want to add the feature.

Any recommendation for implementation is appreciated.

Thanks!

**Comment by onderonur** [comment]
Finally, I got some time to try this feature today.

Firing some function when the window or the parent component is scrolled to a threshold to top is no problem. But the real trick is handling the scrollbar position.

Let's say that you set some prop to use the infinite scroller with an inversed direction. Like `to-top`.
If you start from the bottom of the scrollable parent component, and scroll to top of it, you can  fetch some data, add the new items to the current list and the scroll position will be handled by the browser perfectly (at least I've tested this for `Chrome`).

But when you scroll all the way up (I mean `parentNode.scrollTop = 0`), it gets stuck at there and just constantly fetches data, waits for the response and fetches again. Scrollbar stays at the top.
I've tried things like setting `parentNode.scrollTop = 1` if it's `0` just to force the browser to preserve its position, or saving the previous total height of the container and comparing with the new value to set a scroll position manually.

For now I have no solution for this. I'm testing different ways to handle this and trying to figure out how other packages overcome this.

Like always, I'm open to any advice.

You can also check the current implementation from `scrolldirection` branch. It has some hacky solution for `scrollContainer: "parent"` type of usage. And I've seen that it works on `Chrome` and `Firefox`.
But it doesn't handle `scrollContainer: "window"` situation. If we find a solution for that, this feature can be ready to be published.

Thanks!

**Comment by onderonur** [comment]
You can also check the current implementation from `scrolldirection` branch. It has some hacky solution for `scrollContainer: "parent"` type of usage. And I've seen that it works on `Chrome` and `Firefox`.
But it doesn't handle `scrollContainer: "window"` situation. If we find a solution for that, this feature can be ready to be published.

**Comment by SuEric** [comment]
Hi @onderonur ,

Is this still worth checking? I am planning on support scroll direction to my app, I will take a look at this if I can make it work.

**Comment by onderonur** [comment]
Hi!

I've just published a new major version (v4) and we have a new API now. I've updated `README.md` and will add a little migration guide to "Releases" section. It's much more easy to create lists with different layouts now.
  
You can check the [demo](https://onderonur.github.io/react-infinite-scroll-hook/) and find all of their source codes on [here](https://github.com/onderonur/react-infinite-scroll-hook/tree/master/example/examples).

Thanks!
