### ISSUE TITLE
Should we map the threshold to a ratio instead of a px? 

### ISSUE THREAD

**Issue by rodrigo-picanco** [onderonur/react-infinite-scroll-hook#8]
Hello everyone, could not find a template for this one. 

I was wondering if the threshold could be a ratio of the container instead of a pixel distance, this representation is common in other infinite-list components and what not and seems to me that relates better with the mindset of "when should we load more" since we live on the world of responsiveness.

I know this might be a breaking change, so we there's should be some caution. Either way, here's an example of what I mean? 

```js

 const infiniteRef = useInfiniteScroll<HTMLDivElement>({
   ...
    threshold:  0.5 // trigger loadMore in the middle of the scroll parent
  })

```
Cheers for the awesomew hook, hope I can help with this one!

**Comment by onderonur** [comment]
Interesting point. That might be very useful actually. But some users of this package may want to stick to `px`. If we could find a clear distinction between `px` and `%`, that would be perfect.
One option is using it like `threshold: "100px"` and `threshold: "50%"`.
`number` may fallback to `px` for backward compatibility.
Not sure about pros/cons of this usage now. I need to try a little I think.

Thanks!

**Comment by rodrigo-picanco** [comment]
Glad to help @onderonur :smile:

**Comment by onderonur** [comment]
Hi!

I've just published a new major version (v4) and we have a new API now.

It uses `IntersectionObserver` under the hood and we can pass `rootMargin` instead of our old `threshold`. `rootMargin` accepts percentage values. For fine tuning, you can check docs for `IntersectionObserver` on your favorite documentation site 🙂.

Thanks again!
