### ISSUE TITLE
Demo works only for html list tags

### ISSUE THREAD

**Issue by gabimoncha** [onderonur/react-infinite-scroll-hook#9]
The repo's demo works only if the container is a List `ul` or `ol`. It should be specified in the README

**Comment by onderonur** [comment]
I don't think `ul` or `ol` is a requirement. I have other projects those I use this hook with other html tags and custom components.
It may be an error specific to demo. Will check it. Thanks!

**Comment by onderonur** [comment]
Hello again. Sorry for the late response but I've checked this issue again. 
I've changed the container list as a `div`. Here is how it looks;

```js
// demo\src\InfiniteList.js

// ...

const List = styled.div`
  list-style: none;
  font-size: 16px;
  margin: 0;
  padding: 6px;
`;

const ListItem = styled.div`
  background-color: #fafafa;
  border: 1px solid #99b4c0;
  padding: 8px;
  margin: 4px;
`;

// Rest of the demo code.
```

![image](https://user-images.githubusercontent.com/50423574/89141703-01a55800-d54e-11ea-93a6-4c78563adaa9.png)

There is no problem with this usage. If you still have this problem and if you can produce a reproduction with a little demo/repo etc, I will check it again. Thanks again!

**Comment by dpramar** [comment]
@gabrielmoncea I just had the same "issue", but it's related to the typings:

![image](https://user-images.githubusercontent.com/6024876/89894400-5134f500-dbda-11ea-8bf0-8156476cdc84.png)

If you check the source code you can see that `useInfiniteScroll` is defined as `useInfiniteScroll<T extends HTMLElement>`

So, the solution is to add the typing of the tag when using the hook. For example, to use the ref in a div:
```
const infiniteRef = useInfiniteScroll<HTMLDivElement>({
    loading,
    hasNextPage,
    onLoadMore: handleLoadMore,
    scrollContainer,
});
```
